name: CI-build-and-push-image-for-dotnetapp

on:
  push:
    branches: [master]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [master]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_FUQUIZLEARN_USERNAME }}
          password: ${{ secrets.DOCKER_FUQUIZLEARN_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_FUQUIZLEARN_USERNAME }}/docker_fuquizlearn:latest, ${{ secrets.DOCKER_FUQUIZLEARN_USERNAME }}/docker_fuquizlearn:${{ github.run_number }}
